platform/plugins/member/routes/web.php
<?php

Route::group([
    'namespace'  => 'Botble\Member\Http\Controllers',
    'prefix'     => BaseHelper::getAdminPrefix(),
    'middleware' => ['web', 'auth'],
], function () {

    Route::group(['prefix' => 'members', 'as' => 'member.'], function () {

        Route::resource('', 'MemberController')->parameters(['' => 'member']);

        Route::delete('items/destroy', [
            'as'         => 'deletes',
            'uses'       => 'MemberController@deletes',
            'permission' => 'member.destroy',
        ]);
    });
});

if (defined('THEME_MODULE_SCREEN_NAME')) {
    Route::group(apply_filters(BASE_FILTER_GROUP_PUBLIC_ROUTE, []), function () {

        Route::group([
            'namespace'  => 'Botble\Member\Http\Controllers',
            'middleware' => ['web'],
            'as'         => 'public.member.',
        ], function () {

            Route::group(['middleware' => ['member.guest']], function () {
                Route::get('login', 'LoginController@showLoginForm')->name('login');
                Route::post('login', 'LoginController@login')->name('login.post');

                Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
                Route::post('register', 'RegisterController@register')->name('register.post');

                Route::get('verify', 'RegisterController@getVerify')->name('verify');

                Route::get('password/request',
                    'ForgotPasswordController@showLinkRequestForm')->name('password.request');
                Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
                Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
                Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
            });

            Route::group([
                'middleware' => [setting('verify_account_email', config('plugins.member.general.verify_email')) ? 'member.guest' : 'member'],
            ], function () {
                Route::get('register/confirm/resend',
                    'RegisterController@resendConfirmation')->name('resend_confirmation');
                Route::get('register/confirm/{email}', 'RegisterController@confirm')->name('confirm');
            });
        });

        Route::group([
            'namespace'  => 'Botble\Member\Http\Controllers',
            'middleware' => ['web', 'member'],
            'as'         => 'public.member.',
        ], function () {
            Route::group([
                'prefix' => 'account',
            ], function () {

                Route::post('logout', 'LoginController@logout')->name('logout');

                Route::get('dashboard', [
                    'as'   => 'dashboard',
                    'uses' => 'PublicController@getDashboard',
                ]);

                Route::get('settings', [
                    'as'   => 'settings',
                    'uses' => 'PublicController@getSettings',
                ]);

                Route::post('settings', [
                    'as'   => 'post.settings',
                    'uses' => 'PublicController@postSettings',
                ]);

                Route::get('security', [
                    'as'   => 'security',
                    'uses' => 'PublicController@getSecurity',
                ]);

                Route::put('security', [
                    'as'   => 'post.security',
                    'uses' => 'PublicController@postSecurity',
                ]);

                Route::post('avatar', [
                    'as'   => 'avatar',
                    'uses' => 'PublicController@postAvatar',
                ]);

            });

            Route::group(['prefix' => 'ajax/members'], function () {
                Route::get('activity-logs', [
                    'as'   => 'activity-logs',
                    'uses' => 'PublicController@getActivityLogs',
                ]);

                Route::post('upload', [
                    'as'   => 'upload',
                    'uses' => 'PublicController@postUpload',
                ]);
            });

            Route::group([
                'prefix' => 'account/posts',
            ], function () {

                Route::get('', [
                    'as'   => 'posts.index',
                    'uses' => 'PostController@index',
                ]);

                Route::get('create', [
                    'as'   => 'posts.create',
                    'uses' => 'PostController@create',
                ]);

                Route::post('create', [
                    'as'   => 'posts.create',
                    'uses' => 'PostController@store',
                ]);

                Route::get('edit/{id}', [
                    'as'   => 'posts.edit',
                    'uses' => 'PostController@edit',
                ]);

                Route::post('edit/{id}', [
                    'as'   => 'posts.edit',
                    'uses' => 'PostController@update',
                ]);

            });

            Route::group(['prefix' => 'ajax/members'], function () {
                Route::delete('delete/{id}', [
                    'as'   => 'posts.destroy',
                    'uses' => 'PostController@delete',
                ]);
                Route::get('tags/all', [
                    'as'   => 'tags.all',
                    'uses' => 'PostController@getAllTags',
                ]);
            });
        });

    });
}

platform/plugins/member/resources/views/layouts/skeleton.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  @if (theme_option('favicon'))
        <link rel="shortcut icon" href="{{ RvMedia::getImageUrl(theme_option('favicon')) }}">
  @endif

  {!! SeoHelper::render() !!}

  <!-- Datetime picker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />

  {!! Assets::renderHeader(['core']) !!}

  {!! Html::style('/vendor/core/css/themes/default.css') !!}

  <!-- Styles -->
  <link href="{{ asset('vendor/core/plugins/member/css/app.css') }}" rel="stylesheet">

  <!-- Put translation key to translate in VueJS -->
  <script type="text/javascript">
      window.trans = JSON.parse('{!! addslashes(json_encode(trans('plugins/member::dashboard'))) !!}');
      var BotbleVariables = BotbleVariables || {};
      BotbleVariables.languages = {
        tables: {!! json_encode(trans('core/base::tables'), JSON_HEX_APOS) !!},
        notices_msg: {!! json_encode(trans('core/base::notices'), JSON_HEX_APOS) !!},
        pagination: {!! json_encode(trans('pagination'), JSON_HEX_APOS) !!},
        system: {
          'character_remain': '{{ trans('core/base::forms.character_remain') }}'
        }
      };
  </script>
</head>
<body>
  @include('core/base::layouts.partials.svg-icon')
  <div id="app">
    @include('plugins/member::components.header')
    <main class="pv3 pv4-ns">
      @yield('content')
    </main>
      @if (count(Assets::getAdminLocales()) > 1)
          <footer>
              <p> {{ trans('core/acl::auth.languages') }}:
                  @foreach (Assets::getAdminLocales() as $key => $value)
                      <span @if (app()->getLocale() == $key) class="active" @endif>
                        <a href="{{ route('settings.language', $key) }}">
                            {!! language_flag($value['flag'], $value['name']) !!} <span>{{ $value['name'] }}</span>
                        </a>
                    </span>
                  @endforeach
              </p>
          </footer>
      @endif
  </div>

  @if (session()->has('status') || session()->has('success_msg') || session()->has('error_msg') || (isset($errors) && $errors->count() > 0) || isset($error_msg))
    <script type="text/javascript">
      window.noticeMessages = [];
      @if (session()->has('success_msg'))
      noticeMessages.push({'type': 'success', 'message': "{!! addslashes(session('success_msg')) !!}"});
      @endif
      @if (session()->has('status'))
      noticeMessages.push({'type': 'success', 'message': "{!! addslashes(session('status')) !!}"});
      @endif
      @if (session()->has('error_msg'))
      noticeMessages.push({'type': 'error', 'message': "{!! addslashes(session('error_msg')) !!}"});
      @endif
      @if (isset($error_msg))
      noticeMessages.push({'type': 'error', 'message': "{!! addslashes($error_msg) !!}"});
      @endif
      @if (isset($errors))
      @foreach ($errors->all() as $error)
      noticeMessages.push({'type': 'error', 'message': "{!! addslashes($error) !!}"});
        @endforeach
        @endif
    </script>
  @endif

  <!-- Scripts -->
  <script src="{{ asset('vendor/core/plugins/member/js/app.js') }}"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
  {!! Assets::renderFooter() !!}
  @stack('scripts')
  @stack('footer')
  @include('core/media::partials.media')
  <script>
      RV_MEDIA_URL.filebrowserImageBrowseUrl = false;
      RV_MEDIA_URL.media_upload_from_editor = '{{ route('public.member.upload') }}'
  </script>
</body>
</html>

platform/plugins/member/resources/views/settings.blade.php
<div class="flexbox-annotated-section">
    <div class="flexbox-annotated-section-annotation">
        <div class="annotated-section-title pd-all-20">
            <h2>{{ trans('plugins/member::settings.title') }}</h2>
        </div>
        <div class="annotated-section-description pd-all-20 p-none-t">
            <p class="color-note">{{ trans('plugins/member::settings.description') }}</p>
        </div>
    </div>

    <div class="flexbox-annotated-section-content">
        <div class="wrapper-content pd-all-20">
            <div class="form-group">
                <label class="text-title-field"
                       for="verify_account_email">{{ trans('plugins/member::settings.verify_account_email') }}
                </label>
                <div class="ui-select-wrapper">
                    <select name="verify_account_email" class="ui-select" id="verify_account_email">
                        <option value="1" @if (setting('verify_account_email', config('plugins.member.general.verify_email')) == 1) selected @endif>{{ trans('core/base::base.yes') }}</option>
                        <option value="0" @if (setting('verify_account_email', config('plugins.member.general.verify_email')) == 0) selected @endif>{{ trans('core/base::base.no') }}</option>
                    </select>
                    <svg class="svg-next-icon svg-next-icon-size-16">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#select-chevron"></use>
                    </svg>
                </div>
            </div>
        </div>
    </div>
</div>

platform/plugins/member/resources/views/table/actions.blade.php
<div class="table-actions">
    @if (!empty($edit))
        <a href="{{ route($edit, $item->id) }}" class="btn btn-icon btn-sm btn-primary" data-original-title="{{ trans('core/base::tables.edit') }}"><i class="fa fa-edit"></i></a>
    @endif

    @if (!empty($delete))
        <a href="#" class="btn btn-icon btn-sm btn-danger deleteDialog" data-section="{{ route($delete, $item->id) }}" role="button" data-original-title="{{ trans('core/base::tables.delete_entry') }}" >
            <i class="fa fa-trash"></i>
        </a>
    @endif
</div>

platform/plugins/member/resources/views/table/base.blade.php
@extends('plugins/member::layouts.skeleton')
@section('content')
<div class="container page-content" style="background: none">
    <div class="table-wrapper">
        @if ($table->isHasFilter())
            <div class="table-configuration-wrap" @if (request()->has('filter_table_id')) style="display: block;" @endif>
                <span class="configuration-close-btn btn-show-table-options"><i class="fa fa-times"></i></span>
                {!! $table->renderFilter() !!}
            </div>
        @endif
        <div class="portlet light bordered portlet-no-padding">
            <div class="portlet-title">
                <div class="caption">
                    <div class="wrapper-action">
                        @if ($actions)
                            <div class="btn-group">
                                <a class="btn btn-secondary dropdown-toggle" href="#" data-toggle="dropdown">{{ trans('core/table::general.bulk_actions') }}
                                </a>
                                <ul class="dropdown-menu">
                                    @foreach ($actions as $action)
                                        <li>
                                            {!! $action !!}
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        @if ($table->isHasFilter())
                            <button class="btn btn-primary btn-show-table-options">{{ trans('core/table::general.filters') }}</button>
                        @endif
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive @if ($actions) table-has-actions @endif @if ($table->isHasFilter()) table-has-filter @endif" style="overflow-x: inherit">
                    @section('main-table')
                        {!! $dataTable->table(compact('id', 'class'), false) !!}
                    @show
                </div>
            </div>
        </div>
    </div>
</div>
@include('core/table::modal')
@endsection
@push('scripts')
    {!! $dataTable->scripts() !!}
@endpush